#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
# Source0 file verified with key 0xFC43F0EE211DFED8 (infra-root@openstack.org)
#
Name     : sahara
Version  : 11.0.0
Release  : 28
URL      : http://tarballs.openstack.org/sahara/sahara-11.0.0.tar.gz
Source0  : http://tarballs.openstack.org/sahara/sahara-11.0.0.tar.gz
Source1  : sahara-all.service
Source2  : sahara-api.service
Source3  : sahara-engine.service
Source4 : http://tarballs.openstack.org/sahara/sahara-11.0.0.tar.gz.asc
Summary  : Sahara project
Group    : Development/Tools
License  : Apache-2.0
Requires: sahara-bin = %{version}-%{release}
Requires: sahara-data = %{version}-%{release}
Requires: sahara-license = %{version}-%{release}
Requires: sahara-python = %{version}-%{release}
Requires: sahara-python3 = %{version}-%{release}
Requires: sahara-services = %{version}-%{release}
Requires: Babel
Requires: Flask
Requires: Jinja2
Requires: SQLAlchemy
Requires: WebOb
Requires: alembic
Requires: botocore
Requires: castellan
Requires: eventlet
Requires: iso8601
Requires: jsonschema
Requires: keystoneauth1
Requires: keystonemiddleware
Requires: oslo.concurrency
Requires: oslo.config
Requires: oslo.context
Requires: oslo.db
Requires: oslo.i18n
Requires: oslo.log
Requires: oslo.messaging
Requires: oslo.middleware
Requires: oslo.policy
Requires: oslo.rootwrap
Requires: oslo.serialization
Requires: oslo.service
Requires: oslo.upgradecheck
Requires: oslo.utils
Requires: paramiko
Requires: pbr
Requires: python-cinderclient
Requires: python-glanceclient
Requires: python-heatclient
Requires: python-keystoneclient
Requires: python-manilaclient
Requires: python-neutronclient
Requires: python-novaclient
Requires: python-swiftclient
Requires: requests
Requires: six
Requires: stevedore
Requires: tooz
BuildRequires : Babel
BuildRequires : Flask
BuildRequires : Jinja2
BuildRequires : SQLAlchemy
BuildRequires : WebOb
BuildRequires : alembic
BuildRequires : botocore
BuildRequires : buildreq-distutils3
BuildRequires : castellan
BuildRequires : eventlet
BuildRequires : iso8601
BuildRequires : jsonschema
BuildRequires : keystoneauth1
BuildRequires : keystonemiddleware
BuildRequires : oslo.concurrency
BuildRequires : oslo.config
BuildRequires : oslo.context
BuildRequires : oslo.db
BuildRequires : oslo.i18n
BuildRequires : oslo.log
BuildRequires : oslo.messaging
BuildRequires : oslo.middleware
BuildRequires : oslo.policy
BuildRequires : oslo.rootwrap
BuildRequires : oslo.serialization
BuildRequires : oslo.service
BuildRequires : oslo.upgradecheck
BuildRequires : oslo.utils
BuildRequires : paramiko
BuildRequires : pbr
BuildRequires : python-cinderclient
BuildRequires : python-glanceclient
BuildRequires : python-heatclient
BuildRequires : python-keystoneclient
BuildRequires : python-manilaclient
BuildRequires : python-neutronclient
BuildRequires : python-novaclient
BuildRequires : python-swiftclient
BuildRequires : requests
BuildRequires : six
BuildRequires : stevedore
BuildRequires : tooz

%description
Sahara Default Template CLI
===========================
The *sahara-templates* application is a simple CLI for managing default
templates in Sahara. This document gives an overview of default templates
and explains how to use the CLI.

%package bin
Summary: bin components for the sahara package.
Group: Binaries
Requires: sahara-data = %{version}-%{release}
Requires: sahara-license = %{version}-%{release}
Requires: sahara-services = %{version}-%{release}

%description bin
bin components for the sahara package.


%package data
Summary: data components for the sahara package.
Group: Data

%description data
data components for the sahara package.


%package license
Summary: license components for the sahara package.
Group: Default

%description license
license components for the sahara package.


%package python
Summary: python components for the sahara package.
Group: Default
Requires: sahara-python3 = %{version}-%{release}

%description python
python components for the sahara package.


%package python3
Summary: python3 components for the sahara package.
Group: Default
Requires: python3-core

%description python3
python3 components for the sahara package.


%package services
Summary: services components for the sahara package.
Group: Systemd services

%description services
services components for the sahara package.


%prep
%setup -q -n sahara-11.0.0

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1571241613
# -Werror is for werrorists
export GCC_IGNORE_WERROR=1
export CFLAGS="$CFLAGS -fno-lto "
export FCFLAGS="$CFLAGS -fno-lto "
export FFLAGS="$CFLAGS -fno-lto "
export CXXFLAGS="$CXXFLAGS -fno-lto "
export MAKEFLAGS=%{?_smp_mflags}
python3 setup.py build

%install
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/sahara
cp %{_builddir}/sahara-11.0.0/LICENSE %{buildroot}/usr/share/package-licenses/sahara/57aed0b0f74e63f6b85cce11bce29ba1710b422b
python3 -tt setup.py build  install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----
mkdir -p %{buildroot}/usr/lib/systemd/system
install -m 0644 %{SOURCE1} %{buildroot}/usr/lib/systemd/system/sahara-all.service
install -m 0644 %{SOURCE2} %{buildroot}/usr/lib/systemd/system/sahara-api.service
install -m 0644 %{SOURCE3} %{buildroot}/usr/lib/systemd/system/sahara-engine.service
## install_append content
install -d -m 755 %{buildroot}/usr/share/defaults
mv %{buildroot}/usr/etc/sahara %{buildroot}/usr/share/defaults/
rm -rf %{buildroot}/usr/etc
## install_append end

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/_sahara-subprocess
/usr/bin/sahara-all
/usr/bin/sahara-api
/usr/bin/sahara-db-manage
/usr/bin/sahara-engine
/usr/bin/sahara-image-pack
/usr/bin/sahara-rootwrap
/usr/bin/sahara-status
/usr/bin/sahara-templates
/usr/bin/sahara-wsgi-api

%files data
%defattr(-,root,root,-)
/usr/share/defaults/sahara/api-paste.ini
/usr/share/defaults/sahara/rootwrap.conf
/usr/share/defaults/sahara/rootwrap.d/sahara.filters

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/sahara/57aed0b0f74e63f6b85cce11bce29ba1710b422b

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*

%files services
%defattr(-,root,root,-)
/usr/lib/systemd/system/sahara-all.service
/usr/lib/systemd/system/sahara-api.service
/usr/lib/systemd/system/sahara-engine.service
